# Generated by Django 6.0.5 on 2026-05-29 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('food_type', models.CharField(max_length=100)),
                ('flavor_type', models.CharField(max_length=100)),
                ('buying_price', models.IntegerField(blank=True, null=True)),
                ('appears_at_resto', models.BooleanField(default=False)),
                ('smell', models.CharField(blank=True, max_length=100, null=True)),
                ('tastes_bad', models.BooleanField(default=False)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('temperature', models.CharField(blank=True, max_length=50, null=True)),
                ('america_availability', models.BooleanField(default=False)),
                ('asia_availability', models.BooleanField(default=False)),
                ('europe_availability', models.BooleanField(default=False)),
                ('japan_availability', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='tomodachi.foodcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FoodPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('Absolutely Love', 'Absolutely Love'), ('Really Like', 'Really Like'), ('Like (Jump)', 'Like (Jump)'), ('Like', 'Like'), ("Didn't Like", "Didn't Like"), ("Really Didn't Like", "Really Didn't Like"), ('Loathes', 'Loathes')], max_length=20)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='tomodachi.food')),
                ('mii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='tomodachi.mii')),
            ],
            options={
                'unique_together': {('mii', 'food')},
            },
        ),
    ]
