# Generated by Django 6.0.5 on 2026-05-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomodachi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='internal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
