# Generated by Django 6.0.5 on 2026-05-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomodachi', '0002_food_internal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='flavor_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
